---

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Touch a file to ensure it exists
      lineinfile: dest='./sample_file' line="it's alive!" create=yes state=present

